global:
  sysdig:
    accessKey: [ACCESS_KEY]
    region: eu1
  clusterConfig:
    name: [CLUSTER_NAME]
  kspm:
    deploy: true  

clusterScanner:
  enabled: false

kspmCollector:
  enabled: false

admissionController:
  enabled: false

nodeAnalyzer:
  enabled: true
  nodeAnalyzer:
    runtimeScanner:
      deploy: false
    hostScanner:
      deploy: true
      scanOnStart: true
    benchmarkRunner:
      deploy: false
    hostAnalyzer:
      deploy: true
    imageAnalyzer:
      deploy: false

agent:
  monitor:
    enabled: false
  ebpf:
    enabled: true
    kind: universal_ebpf # If node kernel is >5.8
  privileged: false # If node kernel is >5.8 or OS is RHCOS
  sysdig:
    settings:
      feature:
        mode: secure_light
  resources:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 100Mi

clusterShield:
  enabled: true
  cluster_shield:
    features:
      admission_control:
        enabled: false
      audit:
        enabled: true
      container_vulnerability_management:
        enabled: true
      posture:
        enabled: true