apiVersion: apps/v1
kind: Deployment
metadata:
  name: safeapp-deployment
  labels:
    app: nginx-safe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-safe-app
  template:
    metadata:
      labels:
        app: nginx-safe-app
    spec:
      containers:
      - name: nginx-safe-app
        image: nginx:1.14.2
        ports:
        - containerPort: 80
